import {
  EXPORT_NAMES,
  JOB_KEYS,
  MANAGED_RESOURCE_KEYS,
  IJT_MANAGED_ROUTINE_SET,
  PAGE_ROUTE,
  PLUGIN_ID,
  PLUGIN_VERSION,
  ROUTE_KEYS,
  SLOT_IDS,
} from "./constants.js";

const manifest = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: PLUGIN_VERSION,
  displayName: "Monolith Fleet Connector",
  description: "Connects Paperclip companies and agents to Monolith Fleet API health, repair, routine reconciliation, and cost-sync operations.",
  author: "Raava",
  categories: ["connector", "automation", "ui"],
  capabilities: [
    "companies.read",
    "agents.read",
    "activity.log.write",
    "metrics.write",
    "plugin.state.read",
    "plugin.state.write",
    "jobs.schedule",
    "api.routes.register",
    "http.outbound",
    "secrets.read-ref",
    "instance.settings.register",
    "ui.sidebar.register",
    "ui.page.register",
    "ui.detailTab.register",
    "ui.dashboardWidget.register",
    "ui.action.register",
    "agents.managed",
    "projects.managed",
    "routines.managed",
  ],
  entrypoints: {
    worker: "./src/worker.js",
    ui: "./src/ui",
  },
  agents: [
    {
      agentKey: MANAGED_RESOURCE_KEYS.agent,
      displayName: "Fleet Governance Operator",
      role: "operations",
      title: "Managed outcomes reviewer",
      icon: "radar",
      capabilities: "Reviews Monolith Fleet health, budget, routine-drift, and lifecycle evidence for a mapped Paperclip company. Proposes board-approved changes instead of directly mutating Fleet.",
      status: "paused",
      adapterPreference: ["codex_local", "claude_local", "opencode_local", "gemini_local", "cursor", "process", "http"],
      adapterConfig: {},
      permissions: {},
      instructions: {
        entryFile: "AGENTS.md",
        content: [
          "# Fleet Governance Operator",
          "",
          "You review Monolith Fleet evidence through the Paperclip Fleet Connector.",
          "Use Paperclip issues, comments, activity, and connector data as the durable work record.",
          "Do not pause, resume, register, repair, request routine repair, or apply cost sync unless the issue includes an explicit board approval or Monolith change-request reference.",
          "When reporting, cite the tenant, company, connector check time, Fleet health, budget signals, routine reconciliation status, and any recovery recommendation.",
        ].join("\n"),
      },
    },
  ],
  projects: [
    {
      projectKey: MANAGED_RESOURCE_KEYS.project,
      displayName: "Monolith Fleet Operations",
      description: "Connector-managed project for Fleet health, budget governance, routine drift, and approved lifecycle change requests.",
      status: "in_progress",
      color: "#0f766e",
      settings: {
        surface: "fleet-connector",
        authorityBoundary: "Paperclip records governance; Monolith Fleet remains runtime authority.",
      },
    },
  ],
  routines: [
    {
      routineKey: MANAGED_RESOURCE_KEYS.routine,
      title: "Review Fleet managed outcome signals",
      description: "Review linked Fleet agents, budget incidents, routine reconciliation drift, cost-sync posture, and lifecycle requests for the mapped Monolith tenant. Summarize evidence and propose board-approved changes; do not apply lifecycle or cost changes without an explicit approval or change-request reference.",
      assigneeRef: { resourceKind: "agent", resourceKey: MANAGED_RESOURCE_KEYS.agent },
      projectRef: { resourceKind: "project", resourceKey: MANAGED_RESOURCE_KEYS.project },
      status: "paused",
      priority: "high",
      concurrencyPolicy: "coalesce_if_active",
      catchUpPolicy: "skip_missed",
      triggers: [
        {
          kind: "schedule",
          label: "Daily governance review",
          enabled: false,
          cronExpression: "0 13 * * *",
          timezone: "America/New_York",
        },
      ],
      issueTemplate: {
        surfaceVisibility: "plugin_operation",
        originId: "operation:fleet-governance-review",
        billingCode: "raava:fleet-governance-review",
      },
    },
  ],
  instanceConfigSchema: {
    type: "object",
    properties: {
      fleetApiBaseUrl: {
        type: "string",
        title: "Fleet API Base URL",
        description: "Fleet API origin, for example https://api.fleetos.raavasolutions.com.",
        default: "",
      },
      fleetApiTokenSecretRef: {
        type: "string",
        format: "secret-ref",
        title: "Fleet API Token Secret Ref",
        description: "Paperclip secret reference containing the Fleet API bearer token.",
        default: "",
      },
      tenantIdByCompanyId: {
        type: "object",
        title: "Tenant IDs by Paperclip Company ID",
        additionalProperties: { type: "string" },
        default: {},
      },
      defaultTenantId: {
        type: "string",
        title: "Default Monolith Tenant ID",
        default: "",
      },
      enableRepairActions: {
        type: "boolean",
        title: "Enable Repair Actions",
        default: false,
      },
      enableRoutineRepairActions: {
        type: "boolean",
        title: "Enable Routine Repair Requests",
        default: false,
        description: "Allows the connector to create Fleet Manager routine-repair proposals. Direct repair apply remains blocked.",
      },
      routineRepairRequireApprovalRef: {
        type: "boolean",
        title: "Require Routine Repair Approval Ref",
        default: true,
        description: "Requires an approval or change-request reference before creating a routine-repair proposal.",
      },
      enableRoutineMirrorActions: {
        type: "boolean",
        title: "Enable Approved Routine Mirror",
        default: false,
        description: "Allows the connector to request Fleet Manager approval-bound mirroring of Paperclip-owned routines into Hermes contracts. Direct apply remains blocked.",
      },
      routineMirrorRequireApprovalRef: {
        type: "boolean",
        title: "Require Routine Mirror Approval Ref",
        default: true,
        description: "Requires an approval or change-request reference before requesting routine mirror proposals.",
      },
      enableRegisterActions: {
        type: "boolean",
        title: "Enable Register Existing Agent Actions",
        default: false,
      },
      enableCostSyncActions: {
        type: "boolean",
        title: "Enable Cost Sync Apply",
        default: false,
        description: "Dry-run cost checks are always allowed; non-dry-run apply requires this flag.",
      },
      enableLifecycleActions: {
        type: "boolean",
        title: "Enable Pause/Resume Actions",
        default: false,
        description: "Allows audited Paperclip requests to pause or resume linked Fleet containers. Disabled by default.",
      },
      lifecycleRequireApprovalRef: {
        type: "boolean",
        title: "Require Pause/Resume Approval Ref",
        default: true,
        description: "Requires lifecycle requests to include a Paperclip approval or Monolith change request reference.",
      },
      enableBudgetAlerts: {
        type: "boolean",
        title: "Enable Budget Alerts",
        default: true,
        description: "Routes Fleet budget incidents, pending approvals, and high utilization into Paperclip activity and metrics.",
      },
      budgetAlertUtilizationPercent: {
        type: "integer",
        title: "Budget Alert Utilization Percent",
        default: 90,
        minimum: 1,
        maximum: 100,
      },
      enableScheduledCostSync: {
        type: "boolean",
        title: "Enable Scheduled Cost Sync",
        default: false,
        description: "Runs the scheduled cost-sync job for configured company mappings. Disabled by default.",
      },
      scheduledCostSyncApply: {
        type: "boolean",
        title: "Scheduled Cost Sync Apply",
        default: false,
        description: "When false, the scheduled job dry-runs only. Applying also requires Enable Cost Sync Apply.",
      },
      scheduledCostSyncHours: {
        type: "integer",
        title: "Scheduled Cost Sync Lookback Hours",
        default: 24,
        minimum: 1,
        maximum: 720,
      },
    },
  },
  jobs: [
    {
      jobKey: JOB_KEYS.pollFleetLinks,
      displayName: "Poll Fleet Links",
      description: "Refreshes Fleet health and routine reconciliation state for configured company mappings.",
      schedule: "*/15 * * * *",
    },
    {
      jobKey: JOB_KEYS.scheduledCostSync,
      displayName: "Scheduled Cost Sync",
      description: "Dry-runs or applies Fleet cost sync for configured company mappings when enabled.",
      schedule: "0 * * * *",
    },
  ],
  apiRoutes: [
    {
      routeKey: ROUTE_KEYS.overview,
      method: "GET",
      path: "/fleet/overview",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.linkHealth,
      method: "GET",
      path: "/fleet/link-health",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.routineAuthorityPreview,
      method: "POST",
      path: "/fleet/routine-authority-preview",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.managedRoutineReconciliation,
      method: "POST",
      path: "/fleet/managed-routine-reconciliation",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.dryRunRoutineMirrorStatus,
      method: "POST",
      path: "/fleet/routine-mirror-status",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.approvedRoutineMirror,
      method: "POST",
      path: "/fleet/routine-mirror",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.registerExisting,
      method: "POST",
      path: "/fleet/register-existing",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.repairLink,
      method: "POST",
      path: "/fleet/repair-link",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.routineRepair,
      method: "POST",
      path: "/fleet/routine-repair",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.syncCosts,
      method: "POST",
      path: "/fleet/sync-costs",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.lifecycle,
      method: "POST",
      path: "/fleet/lifecycle",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: ROUTE_KEYS.reconcileManagedResources,
      method: "POST",
      path: "/fleet/managed-resources/reconcile",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
  ],
  ui: {
    slots: [
      {
        type: "dashboardWidget",
        id: SLOT_IDS.dashboardWidget,
        displayName: "Fleet Health",
        exportName: EXPORT_NAMES.dashboardWidget,
      },
      {
        type: "sidebarPanel",
        id: SLOT_IDS.sidebarPanel,
        displayName: "Fleet Connector",
        exportName: EXPORT_NAMES.sidebarPanel,
      },
      {
        type: "page",
        id: SLOT_IDS.page,
        displayName: "Fleet Connector",
        exportName: EXPORT_NAMES.page,
        routePath: PAGE_ROUTE,
      },
      {
        type: "detailTab",
        id: SLOT_IDS.agentTab,
        displayName: "Fleet",
        exportName: EXPORT_NAMES.agentTab,
        entityTypes: ["agent"],
      },
      {
        type: "settingsPage",
        id: SLOT_IDS.settingsPage,
        displayName: "Fleet Connector",
        exportName: EXPORT_NAMES.settingsPage,
      },
    ],
  },
};

manifest.routines.push(
  ...IJT_MANAGED_ROUTINE_SET.routines.map((routine) => ({
    routineKey: routine.routineKey,
    title: routine.title,
    description: routine.description,
    assigneeRef: { resourceKind: "agent", resourceKey: MANAGED_RESOURCE_KEYS.agent },
    projectRef: { resourceKind: "project", resourceKey: MANAGED_RESOURCE_KEYS.project },
    status: "paused",
    priority: "high",
    concurrencyPolicy: "coalesce_if_active",
    catchUpPolicy: "skip_missed",
    triggers: [],
    issueTemplate: {
      surfaceVisibility: "plugin_operation",
      originId: `operation:${routine.routineKey}`,
      billingCode: `raava:${routine.routineKey}`,
      metadata: {
        routineKey: routine.routineKey,
        tenantId: IJT_MANAGED_ROUTINE_SET.tenantId,
        role: routine.role,
        assigneeRuntimeRef: routine.assigneeRuntimeRef,
      },
    },
  })),
);

export default manifest;
